"""
Multi-Engine Deep Learning & Consensus Ranking Matrix for Bindora Dock.

Combines empirical, physics-based, and deep learning scoring metrics into a unified consensus matrix:
1. AutoDock Vina Empirical Score
2. Vinardo Empirical Free Energy
3. MM-GBSA Continuum Physics Solvation Free Energy
4. GNINA / CNN Shape Complementarity & Affinity
5. Ligand Intramolecular Strain Penalty Filtering
6. Targeted Covalent Enthalpy Bonus (when applicable)

NOTE ON POSE LINEAGE & INDEPENDENCE:
AutoDock Vina, Vinardo, and MM-GBSA evaluate identical 3D docked poses (or local energy-minimized
variants thereof) generated by Vina's Monte Carlo conformational search; they do NOT represent
independently sampled binding poses. Vinardo is a re-parameterization of Vina terms, not an
independent engine. True multi-engine consensus requires at least 2 orthogonal evaluation paradigms
(e.g., empirical scoring + continuum physics MM-GBSA or deep convolutional neural networks).
Consensus rank aggregation is rejected as INSUFFICIENT_DATA when n_poses < 3 or < 2 independent engines.
"""

import math
from typing import Dict, Any, List, Optional, Tuple


class ConsensusScoringService:
    """
    Consensus Scoring and Multi-Engine Rank Aggregator.
    Eliminates false-positive decoys by requiring concordant agreement between
    empirical potentials (Vina/Vinardo), physics mechanics (MM-GBSA), and deep learning (CNN).
    """

    DEFAULT_WEIGHTS = {
        "vina": 0.30,
        "vinardo": 0.20,
        "mmgbsa": 0.30,
        "cnn": 0.20
    }

    STRAIN_PENALTY_THRESHOLD = 8.0   # kcal/mol: strain above this begins penalty
    HIGH_STRAIN_CUTOFF = 15.0        # kcal/mol: flags high-strain decoy (> 15.0 kcal/mol)

    @classmethod
    def compute_pose_consensus(
        cls,
        poses: List[Dict[str, Any]],
        weights: Optional[Dict[str, float]] = None,
        covalent_bonus_kcal: float = 0.0
    ) -> List[Dict[str, Any]]:
        """
        Evaluate and re-rank a collection of docked poses using multi-engine consensus matrix.

        Parameters:
            poses: List of pose dictionaries with 'affinity_kcal', optional 'vinardo_affinity_kcal',
                   'mmgbsa_delta_g_kcal', 'gnina', and 'ligand_strain_kcal'.
            weights: Custom weighting dict for scoring terms.
            covalent_bonus_kcal: Optional covalent enthalpy bonus from CovalentDockingService.

        Returns:
            Re-ranked list of poses augmented with consensus scores, ranks, and confidence ratings.
        """
        if not poses:
            return []

        w = dict(cls.DEFAULT_WEIGHTS)
        if weights:
            w.update(weights)

        n = len(poses)

        # 0. Check independent engine availability and pose count
        # Independent engines:
        # 1. Vina (Empirical)
        # 2. MM-GBSA (Continuum Physics, if explicitly computed)
        # 3. GNINA CNN (Deep Learning, if available)
        # (Vinardo is an empirical rescoring of Vina coordinates, not an orthogonal engine)
        has_vina = any(p.get("affinity_kcal") is not None for p in poses)
        has_mmgbsa = any(
            (p.get("mmgbsa_delta_g_kcal") is not None or
             (isinstance(p.get("mmgbsa"), dict) and p.get("mmgbsa", {}).get("mmgbsa_delta_g_kcal") is not None))
            for p in poses
        )
        has_cnn = any(isinstance(p.get("gnina"), dict) and p.get("gnina", {}).get("available") for p in poses)

        independent_engines = []
        if has_vina:
            independent_engines.append("Vina (Empirical)")
        if has_mmgbsa:
            independent_engines.append("MM-GBSA (Continuum Physics)")
        if has_cnn:
            independent_engines.append("GNINA (Deep Learning CNN)")

        n_engines = len(independent_engines)

        is_insufficient_data = False
        insufficient_reason = ""
        if n < 3:
            is_insufficient_data = True
            insufficient_reason = f"Consensus rank aggregation requires at least 3 distinct poses (got {n})."
        elif n_engines < 2:
            is_insufficient_data = True
            engines_str = ", ".join(independent_engines) if independent_engines else "None"
            insufficient_reason = (
                f"Consensus scoring requires at least 2 independent scoring engines (got {n_engines}: {engines_str}). "
                "Note: Vina, Vinardo, and MM-GBSA evaluate identical docked 3D coordinates."
            )

        # 1. Extract values for each metric
        vina_vals = []
        vinardo_vals = []
        mmgbsa_vals = []
        cnn_vals = []
        strain_vals = []

        for p in poses:
            # Vina affinity (kcal/mol, negative is better)
            v_aff = p.get("affinity_kcal")
            vina_vals.append(v_aff if v_aff is not None else 0.0)

            # Vinardo affinity
            vin_aff = p.get("vinardo_affinity_kcal")
            vinardo_vals.append(vin_aff if vin_aff is not None else (v_aff if v_aff is not None else 0.0))

            # MM-GBSA delta G
            gbsa = p.get("mmgbsa_delta_g_kcal")
            if gbsa is None and "mmgbsa" in p and isinstance(p["mmgbsa"], dict):
                gbsa = p["mmgbsa"].get("mmgbsa_delta_g_kcal")
            mmgbsa_vals.append(gbsa if gbsa is not None else (v_aff if v_aff is not None else 0.0))

            # CNN affinity or score
            gnina_dict = p.get("gnina", {})
            cnn_score = None
            if isinstance(gnina_dict, dict) and gnina_dict.get("available"):
                cnn_score = gnina_dict.get("cnn_score")
            if cnn_score is None:
                # Surrogate CNN score in [0.0, 1.0] based on binding efficiency
                s_est = max(0.0, min(1.0, 0.5 - (v_aff or -7.0) / 20.0))
                cnn_score = round(s_est, 3)
            cnn_vals.append(cnn_score)

            # Strain energy
            st = p.get("ligand_strain_kcal")
            strain_vals.append(st if st is not None else 0.0)

        # 2. Compute Z-score normalizations
        def z_score(arr: List[float]) -> List[float]:
            if len(arr) <= 1:
                return [0.0] * len(arr)
            mean = sum(arr) / len(arr)
            std = math.sqrt(sum((x - mean)**2 for x in arr) / len(arr))
            if std < 1e-5:
                return [0.0] * len(arr)
            return [(x - mean) / std for x in arr]

        z_vina = z_score(vina_vals)
        z_vinardo = z_score(vinardo_vals)
        z_mmgbsa = z_score(mmgbsa_vals)
        z_cnn = [-z for z in z_score(cnn_vals)]

        # 3. Calculate Individual Ranks
        def get_ranks(arr: List[float], ascending: bool = True) -> List[int]:
            indexed = list(enumerate(arr))
            indexed.sort(key=lambda x: x[1], reverse=not ascending)
            ranks = [0] * len(arr)
            for r, (idx, _) in enumerate(indexed, 1):
                ranks[idx] = r
            return ranks

        ranks_vina = get_ranks(vina_vals, ascending=True)
        ranks_vinardo = get_ranks(vinardo_vals, ascending=True)
        ranks_mmgbsa = get_ranks(mmgbsa_vals, ascending=True)
        ranks_cnn = get_ranks(cnn_vals, ascending=False)

        # 4. Compute composite consensus score for each pose
        augmented_poses = []
        for i in range(n):
            p_copy = dict(poses[i])

            # Strain penalty: zero below threshold, linear above
            st = strain_vals[i]
            strain_pen = 0.0
            if st > cls.STRAIN_PENALTY_THRESHOLD:
                strain_pen = (st - cls.STRAIN_PENALTY_THRESHOLD) * 0.75

            # Per-pose covalent energy bonus
            p_cov_bonus = (
                poses[i].get("covalent_energy_bonus_kcal") or
                poses[i].get("covalent", {}).get("covalent_energy_bonus_kcal") or
                covalent_bonus_kcal
            )

            # Composite Z-score (lower is better)
            comp_z = (
                w["vina"] * z_vina[i] +
                w["vinardo"] * z_vinardo[i] +
                w["mmgbsa"] * z_mmgbsa[i] +
                w["cnn"] * z_cnn[i] +
                strain_pen +
                p_cov_bonus
            )

            # Mean rank (Borda count rank aggregation)
            mean_rank = (ranks_vina[i] + ranks_vinardo[i] + ranks_mmgbsa[i] + ranks_cnn[i]) / 4.0

            # Rank variance (concordance measure)
            ind_ranks = [ranks_vina[i], ranks_vinardo[i], ranks_mmgbsa[i], ranks_cnn[i]]
            rank_spread = max(ind_ranks) - min(ind_ranks)

            v_val = vina_vals[i]
            m_val = mmgbsa_vals[i]

            # Ligand efficiency-aware thermodynamic thresholding:
            # Calibrate threshold to molecular size (heavy atoms count)
            ha = p_copy.get("heavy_atoms") or p_copy.get("ligand_heavy_atoms")
            if ha is None and "ligand_mol" in p_copy and p_copy["ligand_mol"] is not None:
                try:
                    ha = p_copy["ligand_mol"].GetNumHeavyAtoms()
                except Exception:
                    ha = None

            if ha is not None and ha > 0:
                if ha <= 15:
                    target_le = 0.30
                    threshold_kcal = -max(3.5, round(target_le * ha, 2))
                elif ha <= 30:
                    target_le = 0.23
                    threshold_kcal = -max(5.5, round(target_le * ha, 2))
                else:
                    target_le = 0.17
                    threshold_kcal = -max(6.5, min(7.5, round(target_le * ha, 2)))

                le_actual = round(-v_val / ha, 3)
                is_sub_threshold = (v_val > threshold_kcal)
                sub_threshold_desc = (
                    f"Predicted binding energy ({v_val:.2f} kcal/mol) falls above size-calibrated threshold "
                    f"({threshold_kcal:.2f} kcal/mol, LE={le_actual:.2f} vs required {target_le:.2f} kcal/mol/HA); "
                    "indicates weak non-specific surface adhesion."
                )
            else:
                threshold_kcal = -6.0
                is_sub_threshold = (v_val > threshold_kcal)
                sub_threshold_desc = (
                    f"Predicted binding energy ({v_val:.2f} kcal/mol) falls above default -6.0 kcal/mol threshold; "
                    "indicates weak or non-specific surface adhesion."
                )

            decoy_flag = p_copy.get("decoy_filter_flag") or p_copy.get("mmgbsa", {}).get("decoy_filter_verdict")
            is_grease_decoy = (
                decoy_flag in ("FLAGGED_GREASY_DECOY", "FLAGGED_LIPOPHILIC_AGGREGATOR") or
                bool(p_copy.get("mmgbsa", {}).get("is_grease_ball_decoy", False))
            )

            # Confidence classification & SBDD Decoy Gate
            if is_insufficient_data:
                confidence = "INSUFFICIENT_DATA"
                conf_desc = insufficient_reason
            elif is_grease_decoy:
                confidence = "DECOY_GREASE_BALL"
                decoy_why = p_copy.get("mmgbsa", {}).get("decoy_reason") or "Lacks polar active site complementarity (opportunistic grease)"
                conf_desc = f"Pose flagged as false-positive decoy: {decoy_why}"
            elif st > cls.HIGH_STRAIN_CUTOFF:
                confidence = "DECOY_HIGH_STRAIN"
                conf_desc = f"Pose flagged as high-strain decoy ({st:.1f} kcal/mol > {cls.HIGH_STRAIN_CUTOFF} kcal/mol cutoff)."
            elif is_sub_threshold:
                confidence = "SUB_THRESHOLD_AFFINITY"
                conf_desc = sub_threshold_desc
            elif rank_spread <= 2 and mean_rank <= 2.5:
                confidence = "HIGH_CONFIDENCE"
                conf_desc = "Strong multi-engine concordance across empirical, physics (MM-GBSA), and DL scoring."
            elif rank_spread <= 4 or mean_rank <= 4.0:
                confidence = "MODERATE_CONFIDENCE"
                conf_desc = "Acceptable agreement across scoring engines with moderate rank dispersion."
            else:
                confidence = "DISCORDANT_SCORING"
                conf_desc = "Significant disagreement between empirical Vina and physics/CNN scores; verify solvation contacts."

            p_copy["consensus_score"] = round(comp_z, 3)
            p_copy["borda_mean_rank"] = round(mean_rank, 2)
            p_copy["rank_spread"] = rank_spread
            p_copy["consensus_confidence"] = confidence
            p_copy["consensus_confidence_description"] = conf_desc
            p_copy["individual_ranks"] = {
                "vina": ranks_vina[i],
                "vinardo": ranks_vinardo[i],
                "mmgbsa": ranks_mmgbsa[i],
                "cnn": ranks_cnn[i]
            }
            p_copy["scoring_breakdown"] = {
                "vina_kcal": vina_vals[i],
                "vinardo_kcal": vinardo_vals[i],
                "mmgbsa_kcal": mmgbsa_vals[i],
                "cnn_score": cnn_vals[i],
                "strain_penalty_kcal": round(strain_pen, 2),
                "covalent_bonus_kcal": round(covalent_bonus_kcal, 2)
            }
            p_copy["independent_engines_count"] = n_engines
            p_copy["independent_engines_evaluated"] = independent_engines

            augmented_poses.append(p_copy)

        # 5. Sort by consensus score: decoys and sub-threshold poses automatically relegated to bottom
        augmented_poses.sort(key=lambda x: (
            x["consensus_confidence"] in ("INSUFFICIENT_DATA", "DECOY_HIGH_STRAIN", "DECOY_GREASE_BALL", "SUB_THRESHOLD_AFFINITY"),
            x["consensus_score"]
        ))

        # Assign final consensus ranks
        for final_rank, p in enumerate(augmented_poses, 1):
            p["consensus_rank"] = final_rank

        return augmented_poses

